version: '3.9'
services:
  db:
  image: mysql:8.0
  container_name: mi-mysql
  restart: always
  command: --default-authentication-plugin=mysql_native_password
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=testdb
    - MYSQL_USER=usuario_app
    - MYSQL_PASSWORD=password
  ports:
    - "3306:3306"