# Información de la aplicación
info:
  app:
    encoding: '@project.build.sourceEncoding@'
  java:
    source: '@java.version@'
    target: '@java.version@'
app:
  version: '@0.0.1@'
  name: '@programacion1parcial@'

spring:
  application:
    name: '@programacion1parcial@'

main:
  banner-mode: 'CONSOLE'

datasource:
  url: jdbc:mysql://localhost:3306/testdb
  username: client
  password: password
  driver-class-name: com.mysql.cj.jdbc.Driver
  initialization-mode: always

jpa:
  show-sql: true
  open-in-view: false
  hibernate:
    ddl-auto: update

sql:
  init:
    mode: always
    platform: mysql
    schema-locations: classpath:schema.sql
    data-locations: classpath:data.sql

doc:
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true

server:
  port: 8282
  compression:
  enabled: true

user:
  timezone: 'UTC'

logging:
  config: classpath:log4j2.xml